{% set version = "1.6-6" %}

package:
  name: r-rgdal
  version: {{ version|replace("-", "_") }}

source:
  url:  # [ not win ]
    - {{ cran_mirror }}/src/contrib/rgdal_{{ version }}.tar.gz  # [ not win ]
    - {{ cran_mirror }}/src/contrib/Archive/rgdal/rgdal_{{ version }}.tar.gz  # [ not win ]
  sha256: d742d7aadfc004771e61cac28a1faffeb4dbda981dea19115be11c541087399a  # [ not win ]
  url: https://cran.r-project.org/bin/windows/contrib/{{ r_base[0:3] }}/rgdal_{{ version }}.zip  # [win]
  sha256: 5a7c4e994c4e50a1a77f38bac699cf029dffab5e344a52e931d9b3f19f2c0f04  # [win and r_base=="4.1"]

build:
  number: 5
  merge_build_host: True  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-sp                       # [build_platform != target_platform]
    - posix  # [win]
    - {{ compiler('c') }}    # [not win]
    - {{ compiler('cxx') }}  # [not win]
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - r-base
    - r-sp >=1.1_0
    - libgdal                # [not win]
    - proj                   # [not win]
  run:
    - r-base
    - r-sp >=1.1_0
    - libgdal                # [not win]
    - proj                   # [not win]

test:
  commands:
    - R -e "library('rgdal')"    # [not win]
    - R -e \"library('rgdal')\"  # [win]

about:
  home: http://www.gdal.org, https://r-forge.r-project.org/projects/rgdal/
  license: GPL-2.0-or-later
  license_file: 
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
  summary: 'Provides bindings to Frank Warmerdam''s Geospatial Data Abstraction Library (GDAL)
    (>= 1.6.3) and access to projection/transformation operations from the PROJ.4 library.
    The GDAL and PROJ.4 libraries are external to the package, and, when installing
    the package from source, must be correctly installed first. Both GDAL raster and
    OGR vector map data can be imported into R, and GDAL raster data and OGR vector
    data exported. Use is made of classes defined in the sp package. Windows and Mac
    Intel OS X binaries (including GDAL, PROJ.4 and Expat) are provided on CRAN. '

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf
