{% set version = "1.4-3" %}

package:
  name: r-rgdal
  version: {{ version|replace("-", "_") }}

source:
  fn: rgdal_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/rgdal_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/rgdal/rgdal_{{ version }}.tar.gz
  sha256: 69ce1cb3ff7221482114f964b5636d5e5b1677f13431161ce9d5cca123b54805

build:
  merge_build_host: True  # [win]
  number: 0
  skip: True  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix  # [win]
    - pkg-config  # [osx]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('cxx') }}        # [unix]
    - {{ compiler('m2w64_cxx') }}  # [win]
  host:
    - r-base
    - r-sp >=1.1_0
    - gdal >=1.11.4,<=2.5.0
    - proj4 >=4.8.0
  run:
    - r-base
    - r-sp >=1.1_0
    - gdal >=1.11.4,<=2.5.0
    - proj4 >=4.8.0

test:
  commands:
    - R -e "library('rgdal')"  # [not win]
    - R -e \"library('rgdal')\"  # [win]

about:
  home: http://www.gdal.org, https://r-forge.r-project.org/projects/rgdal/
  license: GPL-3.0
  summary: 'Provides bindings to Frank Warmerdam''s Geospatial Data Abstraction Library (GDAL)
    (>= 1.6.3) and access to projection/transformation operations from the PROJ.4 library.
    The GDAL and PROJ.4 libraries are external to the package, and, when installing
    the package from source, must be correctly installed first. Both GDAL raster and
    OGR vector map data can be imported into R, and GDAL raster data and OGR vector
    data exported. Use is made of classes defined in the sp package. Windows and Mac
    Intel OS X binaries (including GDAL, PROJ.4 and Expat) are provided on CRAN. '

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf
